import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs";

import RQProvider from "@/app/components/RQProvider";
import { ShowsProvider } from "@/app/components/ShowContext";

import { getShows, getVotes } from "@/db";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId }: { userId: string | null } = auth();
  const shows = await getShows();
  const votes = userId ? await getVotes(userId) : [];

  return (
    <html lang="en">
      <body className={`${inter.className} dark max-w-6xl mx-auto`}>
        <ShowsProvider shows={shows} votes={votes}>
          <RQProvider>
            <ClerkProvider>{children}</ClerkProvider>
          </RQProvider>
        </ShowsProvider>
      </body>
    </html>
  );
}
