import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs";

import RQProvider from "./components/RQProvider";
import "./globals.css";

import { getShows, getVotes } from "@/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId }: { userId: string | null } = auth();
  const shows = await getShows();
  const votes = userId ? await getShows() : [];
  console.log({ shows, votes });

  return (
    <html lang="en">
      <body className={`${inter.className} dark max-w-6xl mx-auto`}>
        <RQProvider>
          <ClerkProvider>{children}</ClerkProvider>
        </RQProvider>
      </body>
    </html>
  );
}
